version: "3.8"
services:
    mail_service:
        container_name: mail-service
        image: jacksonveroneze/mail-service:latest
        restart: always
        tty: true
        environment:
            - ASPNETCORE_URLS=http://+:80
            - DOTNET_RUNNING_IN_CONTAINER=true
            - ASPNETCORE_ENVIRONMENT=Production
            - APP_CONFIG_Urls_Allow_Cors=*;
            - APP_CONFIG_Serilog__MinimumLevel__Default=Information
            - APP_CONFIG_Serilog__MinimumLevel__Override__Microsoft=Information
            - APP_CONFIG_Serilog__MinimumLevel__Override__System=Information
            - APP_CONFIG_SmtpSettings__SmtpHost=in-v3.mailjet.com
            - APP_CONFIG_SmtpSettings__SmtpPort=587
            - APP_CONFIG_SmtpSettings__SmtpUser=
            - APP_CONFIG_SmtpSettings__SmtpPass=
            - APP_CONFIG_Jaeger__Enabled=true
            - APP_CONFIG_Jaeger__AgentHost=172.17.0.1
            - APP_CONFIG_Jaeger__AgentPort=6831
            - APP_CONFIG_Hangfire__Storage=Redis
            - APP_CONFIG_Hangfire__RedisConnectionString=redis:6379
        healthcheck:
            test: curl --silent --fail http://mail_service/health || exit 1
            interval: 60s
            timeout: 3s
            start_period: 5s
            retries: 3
        ports:
            - "8089:80"
        logging:
            driver: "json-file"
            options:
                max-file: "2"
                max-size: "1m"
        deploy:
            resources:
                limits:
                    cpus: 0.50
                    memory: 256M
                reservations:
                    memory: 128M

    redis:
        image: redis:6.2-alpine
        ports:
            - "6379:6379"

    redis-admin:
        image: faktiva/php-redis-admin
        container_name: pra
        environment:
            - PHPREDMIN_DATABASE_REDIS_0_HOST=redis
        ports:
            - "8081:80"
        depends_on:
            - redis
