name: Create Release

on:
    release:
        types:
            - created
env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
    DOTNET_ROOT: "/home/runner/.dotnet/app"

jobs:
    install-dotnet-sdk:
        name: Install .NET SDK
        runs-on: ubuntu-20.04

        steps:
            - uses: actions/checkout@v2
            - name: Setup .NET
              uses: actions/setup-dotnet@v1
              with:
                  dotnet-version: '5.0.x'

    generate-publish-docker:
        name: Generate and Publish Docker Image
        runs-on: ubuntu-20.04
        needs: install-dotnet-sdk

        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Login
              run: |
                  echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

            - name: Build
              run: |
                  docker build . -t stock-service:$(echo ${GITHUB_REF:10})

            - name: Create TAG
              run: |
                  docker tag stock-service:$(echo ${GITHUB_REF:10}) jacksonveroneze/mail-service:latest

            - name: Push
              run: |
                  docker push jacksonveroneze/mail-service:latest
